WebDropDead/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:show, :new, :create] do
    resources :games, only: [:new, :create, :show] do
      post :repeat, on: :member
    end
    resources :game_histories, only: [:index, :show, :create] do
      collection do
        post :select_game
      end
    end  
  end

  resource :session, only: [:new, :create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

WebDropDead/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_one :game_history, dependent: :destroy

  validates :num_players, :num_sides, :num_dice, presence: true
  validates :num_sides, numericality: { greater_than_or_equal_to: 2, message: "must be at least 2" }
end

WebDropDead/app/controllers/games_controller.rb
require 'drop_dead_dice_game/auto_drop_dead'
require 'drop_dead_dice_game/die'
require 'drop_dead_dice_game/game_play'
require 'drop_dead_dice_game/player'

class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :repeat]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @user = User.find(params[:user_id])
    @result = run_auto_drop_dead(@game.num_players, @game.num_sides, @game.num_dice)
  end

  # GET /games/new
  def new
    @game = Game.new
    @user = User.find(params[:user_id])
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @user = User.find(params[:user_id])
    @game = @user.games.build(game_params) 
    # @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        @result = run_auto_drop_dead(@game.num_players, @game.num_sides, @game.num_dice)
        @game.update(result: @result)
        @game_history = GameHistory.create(game_id: @game.id, user_id: @user.id, date_played: Time.current.in_time_zone("EST"))

        format.html { redirect_to user_game_path(@user, @game), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        flash.now[:error] = @game.errors.full_messages.join(", ")
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # repeats the game by creating a new game instance with the same parameters
  def repeat
    @user = User.find(params[:user_id])
    @game = Game.find(params[:id])
    @result = run_auto_drop_dead(@game.num_players, @game.num_sides, @game.num_dice)
    @new_game = @user.games.create(num_players: @game.num_players, num_sides: @game.num_sides, num_dice: @game.num_dice, result: @result)
    GameHistory.create(game_id: @new_game.id, user_id: @user.id, date_played: Time.current.in_time_zone("EST"))
    redirect_to user_game_path(@user, @new_game)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:num_players, :num_sides, :num_dice, :result, :user_id)
    end

    def run_auto_drop_dead(num_players, num_sides, num_dice)
      result = AutoDropDead.new.play_game(num_sides, num_dice, num_players)
      result
    end
end

WebDropDead/app/helpers/games_helper.rb
module GamesHelper
end

WebDropDead/app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :num_players %>
    <%= form.number_field :num_players %>
  </div>

  <div class="field">
    <%= form.label :num_sides %>
    <%= form.number_field :num_sides %>
  </div>

  <div class="field">
    <%= form.label :num_dice %>
    <%= form.number_field :num_dice %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.text_field :result %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

WebDropDead/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

WebDropDead/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Num players</th>
      <th>Num sides</th>
      <th>Num dice</th>
      <th>Result</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.num_players %></td>
        <td><%= game.num_sides %></td>
        <td><%= game.num_dice %></td>
        <td><%= game.result %></td>
        <td><%= game.user_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

WebDropDead/app/views/games/new.html.erb
<h1>Play Drop Dead Dice Game</h1>

<% if flash[:error] %>
  <p style="color:red;"><%= flash[:error] %></p>
<% end %>

<%= form_with model: @game, url: user_games_path(@user), local: true do |form| %>
  <%= form.label :number_of_players %>
  <%= form.number_field :num_players %>

  <%= form.label :number_of_sides %>
  <%= form.number_field :num_sides %>

  <%= form.label :number_of_dice %>
  <%= form.number_field :num_dice %>

  <%= form.submit 'Submit' %>
  <br><br>
  <%= link_to 'Go Back', user_path(@user) %>
<% end %>

WebDropDead/app/views/games/show.html.erb
<h1>Drop Dead Dice Game Results</h1>

<p>
  <strong>Game ID:</strong> <%= @game.id %><br>
  <strong>Number of Players:</strong> <%= @game.num_players %><br>
  <strong>Number of Sides:</strong> <%= @game.num_sides %><br>
  <strong>Number of Dice:</strong> <%= @game.num_dice %><br>
  <div style="border: 1px solid black; padding: 10px; margin-top: 10px;">
    <strong>AutoDropDead Result:</strong>
    <%= simple_format(@game.result) %>
  </div>
</p>

<br>
<%= button_to 'Play Again', repeat_user_game_path(@user, @game), method: :post %>
<br>
<%= link_to 'Change Settings', new_user_game_path %>
<br><br>
<%= link_to 'Go Back', user_path(@user) %>