WebDropDead/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: [:show, :new, :create] do
    resources :games, only: [:new, :create, :show] do
      post :repeat, on: :member
    end
    resources :game_histories, only: [:index, :show, :create] do
      collection do
        post :select_game
      end
    end  
  end

  resource :session, only: [:new, :create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

WebDropDead/app/models/game_history.rb
class GameHistory < ApplicationRecord
  belongs_to :game
  belongs_to :user

  before_create :set_user_game_history_id

  private

  # game history id based on both user and game (not just auto-incremented value in db)
  def set_user_game_history_id
    max_id = GameHistory.where(user_id: user_id).maximum(:user_game_history_id)
    self.user_game_history_id = max_id ? max_id + 1 : 1
  end
end

WebDropDead/app/controllers/game_histories_controller.rb
class GameHistoriesController < ApplicationController
  before_action :set_game_history, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /game_histories
  # GET /game_histories.json
  def index
    @game_histories = GameHistory.where(user_id: @user.id)
  end

  # GET /game_histories/1
  # GET /game_histories/1.json
  def show
    @game_history = GameHistory.find(params[:id])
    @game = @game_history.game
  end

  # GET /game_histories/new
  def new
    @game_history = GameHistory.new
  end

  # GET /game_histories/1/edit
  def edit
  end

  # POST /game_histories
  # POST /game_histories.json
  def create
    @game_history = GameHistory.new(game_history_params)

    respond_to do |format|
      if @game_history.save
        format.html { redirect_to @game_history, notice: 'Game history was successfully created.' }
        format.json { render :show, status: :created, location: @game_history }
      else
        format.html { render :new }
        format.json { render json: @game_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_histories/1
  # PATCH/PUT /game_histories/1.json
  def update
    respond_to do |format|
      if @game_history.update(game_history_params)
        format.html { redirect_to @game_history, notice: 'Game history was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_history }
      else
        format.html { render :edit }
        format.json { render json: @game_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_histories/1
  # DELETE /game_histories/1.json
  def destroy
    @game_history.destroy
    respond_to do |format|
      format.html { redirect_to game_histories_url, notice: 'Game history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_game
    @game_history = GameHistory.find_by(user_id: params[:user_id], user_game_history_id: params[:user_game_history_id])
    
    if @game_history
      redirect_to user_game_history_path(params[:user_id], @game_history)
    else
      flash[:alert] = "Game history not found."
      redirect_to user_game_histories_path(params[:user_id])
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_history
      @game_history = GameHistory.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def game_history_params
      params.require(:game_history).permit(:game_id, :user_id, :date_played)
    end
end

WebDropDead/app/helpers/game_histories_helper.rb
module GameHistoriesHelper
end

WebDropDead/app/views/game_histories/_form.html.erb
<%= form_with(model: game_history) do |form| %>
  <% if game_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_history.errors.count, "error") %> prohibited this game_history from being saved:</h2>

      <ul>
        <% game_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.text_field :game_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :date_played %>
    <%= form.datetime_select :date_played %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

WebDropDead/app/views/game_histories/edit.html.erb
<h1>Editing Game History</h1>

<%= render 'form', game_history: @game_history %>

<%= link_to 'Show', @game_history %> |
<%= link_to 'Back', game_histories_path %>

WebDropDead/app/views/game_histories/index.html.erb
<h2>Game History</h2>

<% if flash[:alert] %>
  <p style="color: red;"><%= flash[:alert] %></p>
<% end %>

<% if @game_histories.any? %>
  <ul>
    <% @game_histories.each do |game_history| %>
      <li>Game History ID: <%= game_history.user_game_history_id %> | Played At: <%= game_history.date_played %></li>
    <% end %>
  </ul>
<% else %>
  <p>No saved games available.</p>
<% end %>

<h3>Select a Game by History ID</h3>
<%= form_with url: select_game_user_game_histories_path(@user), method: :post, local: true do |form| %>
  <%= form.label :user_game_history_id, "Game History ID" %>
  <%= form.text_field :user_game_history_id %>
  <%= form.submit "Select Game" %>
<% end %>
<br>
<%= link_to 'Go Back', user_path(@user) %>

WebDropDead/app/views/game_histories/new.html.erb
<h1>New Game History</h1>

<%= render 'form', game_history: @game_history %>

<%= link_to 'Back', game_histories_path %>

WebDropDead/app/views/game_histories/show.html.erb
<h1>Game History</h1>

<p>
  <strong>Game ID:</strong> <%= @game.id %><br>
  <strong>Number of Players:</strong> <%= @game.num_players %><br>
  <strong>Number of Sides:</strong> <%= @game.num_sides %><br>
  <strong>Number of Dice:</strong> <%= @game.num_dice %><br>
  <strong>Date Played:</strong> <%= @game_history.date_played %>
  <div style="border: 1px solid black; padding: 10px; margin-top: 10px;">
    <strong>AutoDropDead Result:</strong>
    <%= simple_format(@game.result) %>
  </div>
</p>

<%= link_to 'Go Back', user_game_histories_path(@user) %>
<%= link_to 'Exit', new_session_path %>